title: ZimaBoard
subtitle: "ZimaBoard, NAS, single board computer, SBC, media server, Plex, edge device, iot gateway,  Filecoin, openwrt, homebridge, pfsense, linux server"
description: "ZimaBoard is world's first hackable single board server. It is a hybird of micro server and SBC (single board computer). It's designed for building a low cost NAS, media server, and software router as your home automation and entertainment center."
author: ZimaBoard
language: en
timezone: UTC

url: https://docs.zimaboard.com
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: false
marked:
  prependRoot: true
  postAsset: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: zima

highlight:
  enable: true
  line_number: false

google_analytics: G-EKB9X0WRP9
fb_admins: 298662541343433
twitter: zimaboard
