name: Build and Deploy Zima-Docs
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@main
      
    - name: Install and Build 🔧 
      run: |
        npm install -g hexo-cli
        yarn install
        hexo -v
        hexo clean
        hexo generate

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
        BASE_BRANCH: main